### ISSUE TITLE
Sign In Failed - Need default main_currency

### ISSUE THREAD

**Issue by kascheri12** [rotkehlchenio/rotkehlchen#123]
Running from source with latest on osx. 
Getting "Sign In Failed" "main_currency not returned from db_settings"
but - the sign in is actually successful and I get logged in.

**Comment by kascheri12** [comment]
It seems [this block of code](https://github.com/rotkehlchenio/rotkehlchen/blob/b2addfdb1cee4e96630a48cd49eb24abcfb5e4ed/ui/userunlock.js#L166) is keeping me from signing in successfully. This is probably the cause of #122

**Comment by kascheri12** [comment]
To initialize the value in my db so that I could achieve a successful sign-in - I commented [this block](https://github.com/rotkehlchenio/rotkehlchen/blob/b2addfdb1cee4e96630a48cd49eb24abcfb5e4ed/ui/userunlock.js#L166-L172) and added this block:
```
                    client.invoke("set_main_currency", "USD", (error, res) => {
                        if(error) {
                            showError('Error', 'Error at setting main currency: ' + error);
                        } else {
                            set_ui_main_currency("USD");
                        }
                    });
```

I only needed this for one execution. After a successful login, I closed rotkehlchen, reverted my changes, restarted the application, and had a successful sign-on.

**Comment by LefterisJP** [comment]
Thank you for the report @kascheri12 

Once your DB data are initialized rotkehlchen always expects it to be there. Do you have any idea how this situation happened? I would like to understand how you ended up in this situation to see what the proper way to fix this would be.

**Comment by kascheri12** [comment]
Whenever I create a new account, I receive the Sign In Failed message like above.

**Comment by LefterisJP** [comment]
Hey @kascheri12 sorry for the slow responses. I was on vacation.

[This](https://github.com/rotkehlchenio/rotkehlchen/pull/125) PR should fix your problem. I wonder how this bug got in there and I had not noticed it until now.

Thanks.
