### ISSUE TITLE
Tax Report generates over the top of itself

### ISSUE THREAD

**Issue by kascheri12** [rotkehlchenio/rotkehlchen#126]
After a Tax Report is generated for a time period (example: 7/1/2018-7/31/2018) then I change the date range to 8/1/2018-8/23/2018 and click Generate Report a second time. The screen doesn't look right, see screenshot.
<img width="2004" alt="screen shot 2018-08-23 at 10 35 28 pm" src="https://user-images.githubusercontent.com/4165385/44567132-e147ae80-a725-11e8-8394-85010fa28101.png">

**Comment by LefterisJP** [comment]
Thank you @kascheri12. Indeed there was an issue there. Also added a check to not start generating a tax report if one is already being calculated.
