### ISSUE TITLE
Add UI widget showcasing if we are connected to an Ethereum node

### ISSUE THREAD

**Issue by LefterisJP** [rotkehlchenio/rotkehlchen#132]
Add a UI widget to showcase if we are connected to an Ethereum node or if we simply use etherscan to query the chain.

**Comment by kascheri12** [comment]
Hi @LefterisJP do you have an idea in your head of what you're looking for?
I was thinking of following the commit for the [balances updated ui widget](https://github.com/rotkehlchenio/rotkehlchen/commit/bba523b19e9123643699f1a183a53affe87c26c7). 

<img width="912" alt="screen shot 2018-09-18 at 10 22 34 am" src="https://user-images.githubusercontent.com/4165385/45704958-23012480-bb2d-11e8-82e7-e992533c02f9.png">

Please provide feedback for what you'd like to see, I would like to work on this issue.

**Comment by LefterisJP** [comment]
Hey @kascheri12. Thanks for taking an interest in this issue.

For the moment it could be there but I was thinking of having this as an indicator (and perhaps others somewhere on the top of the screen. Separated from the settings and currency menu. And each indicator would be an icon which would show more information if the mouse hovers over it.

For example for the connected to local ethereum node indicator the icon with the brokain chain you have would be the only thing to show. And if someone hovers over it then it would say "[Not] Connected to a local ethereum node"

**Comment by LefterisJP** [comment]
Fixed by https://github.com/rotkehlchenio/rotkehlchen/pull/154
