### ISSUE TITLE
Add icons for all tokens to the UI

### ISSUE THREAD

**Issue by LefterisJP** [rotkehlchenio/rotkehlchen#148]
Mostly a cosmetic change, but would be nice to show the icon of each token along with its name in the UI.

**Comment by dnivi3** [comment]
@LefterisJP the following repository has a bunch of icons (for almost all tokens): https://github.com/atomiclabs/cryptocurrency-icons

**Comment by kascheri12** [comment]
Hi @LefterisJP, I have worked on this utilizing the repo mentioned in the last comment and would like to create a PR and have your review. I don't seem to be able to create a PR.

**Comment by kascheri12** [comment]
<img width="462" alt="screen shot 2018-09-11 at 9 32 13 am" src="https://user-images.githubusercontent.com/4165385/45374355-ba52fe80-b5a6-11e8-84b1-c309f987c613.png">

Still a WIP.

**Comment by LefterisJP** [comment]
Hey @kascheri12 thanks a bunch. I will check the PR.
