### ISSUE TITLE
Cannot see all content of dashboard or user settings when window is small

### ISSUE THREAD

**Issue by kascheri12** [rotkehlchenio/rotkehlchen#156]
## Problem Definition

When window height is less than 964px, I cannot scroll down enough to see the bottom of the dashboard-contents.
When windows height is less than 1020px on User Settings, I cannot scroll all the way down to see all information.
I would expect to be able to scroll all the way to the bottom and view all page contents.

**Comment by LefterisJP** [comment]
Hey thanks for this report. I will take a look at this. Experienced on Linux or OSX?

**Comment by kascheri12** [comment]
I'm on OSX Version 10.13.6 (17G65), here's my display settings:

<img width="780" alt="screen shot 2018-09-22 at 12 09 08 am" src="https://user-images.githubusercontent.com/4165385/45914603-fb93ab80-bdfb-11e8-82b3-f47410615fdb.png">

When I launch rotkehlchen with default settings, I see this: 

<img width="915" alt="screen shot 2018-09-21 at 11 46 16 pm" src="https://user-images.githubusercontent.com/4165385/45914694-7610fb00-bdfd-11e8-81a9-314bef18d91e.png">

When I scroll as far down as possible with only hovering my mouse and not clicking anything at all, this is the extent of my view:

<img width="887" alt="screen shot 2018-09-21 at 11 46 19 pm" src="https://user-images.githubusercontent.com/4165385/45914644-b754db00-bdfc-11e8-8578-68b05d1cd991.png">

When I double click the window header bar to maximize the window, this is my view:
<img width="2004" alt="screen shot 2018-09-21 at 11 46 25 pm" src="https://user-images.githubusercontent.com/4165385/45914652-d6ec0380-bdfc-11e8-9287-41adff79c7df.png">

Similarly, with the User Settings page with default settings I see this:

<img width="912" alt="screen shot 2018-09-22 at 12 25 35 am" src="https://user-images.githubusercontent.com/4165385/45914746-2bdc4980-bdfe-11e8-9936-a4746c1ca635.png">

And when I scroll to the bottom without clicking anything, I can only see this:

<img width="912" alt="screen shot 2018-09-22 at 12 25 42 am" src="https://user-images.githubusercontent.com/4165385/45914752-3d255600-bdfe-11e8-8498-08250ee47b38.png">

And after maximizing, I can see that there is more to view:

<img width="2004" alt="screen shot 2018-09-22 at 12 27 17 am" src="https://user-images.githubusercontent.com/4165385/45914780-b02ecc80-bdfe-11e8-9c08-9f12b7cd94e9.png">

**Comment by kascheri12** [comment]
I'm working on a branch currently that fixes this issue for me but I know display resolution is a tricky thing so I'm not sure if the solution for me is a global solution. I will start PR to share that branch and post screenshots of my resolution.

**Comment by LefterisJP** [comment]
@kascheri12 This may be an OSX thing. I can scroll to the bottom normally in Linux no matter the resolution. Will look at your PR.

**Comment by LefterisJP** [comment]
Should be fixed by: https://github.com/rotkehlchenio/rotkehlchen/pull/162
