### ISSUE TITLE
USD Value for IOTA is incorrect

### ISSUE THREAD

**Issue by kascheri12** [rotkehlchenio/rotkehlchen#173]
## Problem Definition

The usd value reported on my exchange is inconsistent with the usd value that rotkehlchen shows.

I tried to find where the USD value is calculated for exchange assets and I found the following API call: [rotkehlchen.inquirer#L68](https://github.com/kascheri12/rotkehlchen/blob/master/rotkehlchen/inquirer.py#L68) 

The asset "IOTA" uses symbol "IOT" at the api endpoint therefore the incorrect rate is returned when querying: 
https://min-api.cryptocompare.com/data/price?fsym=IOTA&tsyms=USD
vs.
https://min-api.cryptocompare.com/data/price?fsym=IOT&tsyms=USD

**Comment by LefterisJP** [comment]
Yes unfortunately cryptocompare uses abitrary names for some tokens. The reasons is that there exist tokens with the exact same symbols and I suppose they use a first come first serve basis.
