### ISSUE TITLE
Log out button does not work -- needs backend implementation too

### ISSUE THREAD

**Issue by LefterisJP** [rotkehlchenio/rotkehlchen#178]
## Problem Definition

When pressing the logout button the user is not logged out of everything. Instead a blank screen is given and the login prompt is not presented.

![2018-10-04-002253_198x194_scrot](https://user-images.githubusercontent.com/1658405/46442958-d4c66500-c76b-11e8-8772-b95767c34fca.png)

And in the chrome console we get the following error:

![2018-10-04-002214_647x116_scrot](https://user-images.githubusercontent.com/1658405/46442953-ced08400-c76b-11e8-8d5d-a129e179569e.png)

## System Description

Rotkehlchen commit: 97bcd4993911c8458f7694e7341e005c70c2813d
System: Archlinux

## Tasks

- [ ] Create a logout function in the backend [server](https://github.com/rotkehlchenio/rotkehlchen/blob/8ebed0ab3bc1bc61e38c1a88a1abfce0b47e2eb4/rotkehlchen/server.py) that touches the appropriate parts of the backend and logs out the user from everywhere. Make sure this is invoked when "log out" is pressed.

- [ ] If logout is succesful then properly show the rotkehlchen login prompt again.

**Comment by zacherygentry** [comment]
working on it
