### ISSUE TITLE
Pressing "Enter" at sign in prompt should initiate sign-in procedure

### ISSUE THREAD

**Issue by LefterisJP** [rotkehlchenio/rotkehlchen#186]
## Problem Definition

When the user gets the sign in prompt during the startup of the application they have to fill in their username and password to unlock the account.

![2018-10-06-171425_578x430_scrot](https://user-images.githubusercontent.com/1658405/46572876-7a0c5380-c98d-11e8-91e6-f2c135ae2662.png)

Pressing "Enter" does nothing. They have to explicitly click "Sign in". That is kind of annoying.

## Task

Enable pressing of "Enter" at the sign-in prompt to attempt to unlock the user account.

**Comment by schambers** [comment]
I'll take this one. can you assign it to me?

**Comment by LefterisJP** [comment]
@schambers please take it up @schambers. I am afraid github does not allow me to assign to external contributors.

**Comment by schambers** [comment]
ok. np. thanks!

**Comment by schambers** [comment]
Shoot, i submitted the pull request under my other account. its me however

**Comment by LefterisJP** [comment]
This issue is still up for grabs.
