### ISSUE TITLE
Add setting for display of datetime format for the UI

### ISSUE THREAD

**Issue by LefterisJP** [rotkehlchenio/rotkehlchen#194]
## Problem Definition

Currently in the application there is a hardcoded format for each different place a date is shown. It would be rather nice if a new setting is added to specify the way dates should be displayed. Also if it should be displayed in UTC or in the user system's local time. For a suggested format we could go with the python [strftime](https://docs.python.org/3.6/library/datetime.html#strftime-and-strptime-behavior) but perhaps that would be a lot of work to implement. @kelsos is there a javascript way to provide a unix timestamp and a string format and get a date string? Google searches seem to point to a `moment.js` package but it seems crazy to me to need an external package for something so simple.

## Task

- Add a new setting. `ui_date_display_format`. Default value should be `%d/%m/%Y %H:%M:%S %Z `. Depending on the format we choose
- Use that format in the front-end to display timestamps to date strings. The function where this happens is `timestamp_to_date()` seen [here](https://github.com/rotkehlchenio/rotkehlchen/blob/3bd8ac193db26da73fe48768db036c25ecd2a4ff/ui/utils.ts#L23).

**Comment by kelsos** [comment]
I can't find anything specific for formatting based on the same patterns, but I guess with the available apis it should not be hard for us to build something like this, no need to include an extra library. It should be easy to build this.

**Comment by LefterisJP** [comment]
nice! Do you want to handle this?

**Comment by kelsos** [comment]
Yes of course
