### ISSUE TITLE
Coinbase support

### ISSUE THREAD

**Issue by rakanalh** [rotkehlchenio/rotkehlchen#296]
Note sure of #46 is going to be enough as regular people (non-traders) would buy directly from Coinbase. If Gdax APIs provide you with purchases also made on Coinbase, then this issue should be closed.

TBD if this issue is needed.

**Comment by spaceblankey** [comment]
Would love to see support for Coinbase (pro/DGAX) added. I know that's the favorite of many a trader. Also probably BitMex.

**Comment by LefterisJP** [comment]
This request has been prioritized by the request of a premium subscription user
