### ISSUE TITLE
Cryptocompare 125 symbols change on 25th of March 2019

### ISSUE THREAD

**Issue by LefterisJP** [rotkehlchenio/rotkehlchen#331]
## Abstract

On 25th of March 2019, 125 symbols in cryptocompare will change according to this post: https://blog.cryptocompare.com/symbol-ticker-change-for-126-coins-ec28ec14c009

The old symbols will continue to work until 24th of June, but we should complete the remappings on the Rotkehlchen side earlier.

**Comment by vcealicu** [comment]
We will keep the two mappings running in paralel for a lot longer, I would advise you have a look at this in the summer when it's quieter

**Comment by LefterisJP** [comment]
This just became urgent as the old mappings no longer work.
