### ISSUE TITLE
Rotkehlchenio hangs

### ISSUE THREAD

**Issue by tjayrush** [rotkehlchenio/rotkehlchen#337]
## Problem Definition

Provide a description of what is the current problem and why you are raising this issue.
If it's a bug please describe what was the unexpected thing that occured and what was the
expected behaviour.

**The program builds and I am able to run it with `npm start`, but it never really does anything. It looks like it's trying to do something because there's a spinning indicator:**

<img width="484" alt="Rotkehlchen" src="https://user-images.githubusercontent.com/5417918/55754461-b858fd00-5a1a-11e9-973f-d4a35e367108.png">

**But as you can see the dropdown box that opens when I click on the spinning thing is empty. So is the dropdown for messages empty. The 'hover' messages work, and the Settings menu opens, but no menus or buttons respond to anything. It just appears to be hung.**

Rotkehlchen also logs debug information to the `rotkehlchen.log` file. Please attach it to the
issue as it may help us find the source of the issue faster.

[rotkehlchen.log](https://github.com/rotkehlchenio/rotkehlchen/files/3056140/rotkehlchen.log)

### System Description

Here add a detailed description of your system, e.g. output of the following script:

```
uname -a
Darwin Thomass-iMac.local 18.2.0 Darwin Kernel Version 18.2.0: Thu Dec 20 20:46:53 PST 2018; root:xnu-4903.241.1~1/RELEASE_X86_64 x86_64

command -v geth && geth version

N/A using parity

command -v parity && parity --version

/usr/local/bin/parity
Parity Ethereum
  version Parity-Ethereum/v2.3.4-beta-0e95db11d-20190220/x86_64-macos/rustc1.32.0
Copyright 2015-2018 Parity Technologies (UK) Ltd.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

By Wood/Paronyan/Kotewicz/Drwięga/Volf
   Habermeier/Czaban/Greeff/Gotchac/Redmann

command -v rotkehlchen && rotkehlchen version

NO RESPONSE

[ -d .git ] && git rev-parse HEAD

0cd4608548f31a2e2cf56e69345ba41839dc6f61

```

**Comment by LefterisJP** [comment]
Hey @tjayrush that means it probably did not build correctly and front-end can't connect to the backend.
Can you provide the following?

1. In the screenshot above you have a cut-off [X] with errors in the console of electron/chromium. Can you show me what those errors say?
2. Did you follow the installation by source [guide](https://rotkehlchen.readthedocs.io/en/latest/installation_guide.html#id6)? Did you create a venv?
3. If yes to all then can you tell me what starting the backend alone gives you? You can do so with `python -m rotkehlchen`.

Note that the OSX docs may be not totally up to date so if we find some things off we can update them now.

**Comment by tjayrush** [comment]
In the screenshot above you have a cut-off [X] with errors in the console of electron/chromium. Can you show me what those errors say?

<img width="1065" alt="Screen Shot 2019-04-09 at 7 01 07 AM" src="https://user-images.githubusercontent.com/5417918/55795287-6903e280-5a95-11e9-9b10-a1602c6dcc0a.png">


Did you follow the installation by source guide? 

I tried. I had all kinds of problems with the installation steps related to installing `node`. I had to uninstall `node` and reinstall it, but then it worked.

Did you create a venv?

When I type `pip freeze | grep pysqlcipher3` I get `/rotkehlchen:jrush>$ pysqlcipher3==1.0.3`

The remaining commands in that section give this:

```
--------------------------------------------------------------------------------------- 07:01:34
(master)@./rotkehlchen:jrush>$ pip install virtualenv
Requirement already satisfied: virtualenv in /Users/jrush/miniconda3/lib/python3.7/site-packages (16.4.3)
--------------------------------------------------------------------------------------- 07:04:12
(master)@./rotkehlchen:jrush>$ pip install virtualenvwrapper
Requirement already satisfied: virtualenvwrapper in /Users/jrush/miniconda3/lib/python3.7/site-packages (4.8.4)
Requirement already satisfied: virtualenv-clone in /Users/jrush/miniconda3/lib/python3.7/site-packages (from virtualenvwrapper) (0.5.2)
Requirement already satisfied: virtualenv in /Users/jrush/miniconda3/lib/python3.7/site-packages (from virtualenvwrapper) (16.4.3)
Requirement already satisfied: stevedore in /Users/jrush/miniconda3/lib/python3.7/site-packages (from virtualenvwrapper) (1.30.1)
Requirement already satisfied: six>=1.10.0 in /Users/jrush/miniconda3/lib/python3.7/site-packages (from stevedore->virtualenvwrapper) (1.11.0)
Requirement already satisfied: pbr!=2.1.0,>=2.0.0 in /Users/jrush/miniconda3/lib/python3.7/site-packages (from stevedore->virtualenvwrapper) (5.1.3)
--------------------------------------------------------------------------------------- 07:04:25
(master)@./rotkehlchen:jrush>$ export WORKON_HOME=$HOME/.virtualenvs
--------------------------------------------------------------------------------------- 07:04:40
(master)@./rotkehlchen:jrush>$ pico /Users/jrush/.virtualenvs
--------------------------------------------------------------------------------------- 07:05:00
(master)@./rotkehlchen:jrush>$ export PROJECT_HOME=$HOME/Devel
--------------------------------------------------------------------------------------- 07:05:11
(master)@./rotkehlchen:jrush>$ mkdir ~/Devel
--------------------------------------------------------------------------------------- 07:05:17
(master)@./rotkehlchen:jrush>$ source /usr/local/bin/virtualenvwrapper.sh
bash: /usr/local/bin/virtualenvwrapper.sh: No such file or directory
--------------------------------------------------------------------------------------- 07:05:26
(master)@./rotkehlchen:jrush>$
```
On my machine, ` pip install virtualenv` and `pip install virtualenvwrapper` seem to be installing somewhere other than `/usr/local/bin`. Plus, neither the file `$HOME/.virtualenvs` nor the folder `$HOME/Devel` exist. Probably related to that.

If yes to all then can you tell me what starting the backend alone gives you? You can do so with python -m rotkehlchen.

```
(master)@./rotkehlchen:jrush>$ python -m rotkehlchen
start running on tcp://127.0.0.1:4242
```

Note that the OSX docs may be not totally up to date so if we find some things off we can update them now.

**Comment by tjayrush** [comment]
Sorry to be a bother, I'm not all that familiar with node. Is this something you will fix or do I have to revert node? Do you have suggestions on where to go to learn how to install an older version of node if that's what I need to do?

**Comment by kelsos** [comment]
No worries, I am personally using [nvm](https://github.com/creationix/nvm) to manage node.js versions for the development environment. I am not sure if it makes sense for you.

**Comment by LefterisJP** [comment]
@tjayrush 

> Sorry to be a bother, 

It's a pleasure to get feedback on the process. Compiling this thing by source is not easy due to the requirements and nitpicks that node sometimes has. But we will figure it out.

So seems like the backend is working and the error you are getting is indeed a node version related one. It's common to get this and this is why this step exists in the guide.

`npm rebuild zeromq --runtime=electron --target=3.0.0`

Did you invoke the npm rebuild command?

-----

Sidenote: Rotkehlchen also has released version with binaries for both OSX and Linux: https://github.com/rotkehlchenio/rotkehlchen/releases

A release has not been made in quite a while since it's being built up for v1.0 right now but using a release is always an option to go around compiling by source.

**Comment by tjayrush** [comment]
That worked! I guess you can close this. I am seeing a few other issues, but I will open them separately.

**Comment by LefterisJP** [comment]
Thank @tjayrush :heart: 

All issues are more than welcome.
