### ISSUE TITLE
Remote node support

### ISSUE THREAD

**Issue by koeppelmann** [rotkehlchenio/rotkehlchen#350]
## Abstract

I have an Ethereum node in my own network but on a different machine. (Avado/dappnode)
Currently I can only specify a port but I would need to specify a location like: http://my.ethchain.dnp.dappnode.eth:8545

**Comment by LefterisJP** [comment]
Hmm I have been using a local node for so long that I overlooked this. Will implement this soon, and will be in the next release. Thanks for pointing it out.

**Comment by LefterisJP** [comment]
One note, @koeppelmann:  This is but a minor thing, since rotkehlchen does not require an ethereum node connection. If not found it will simply revert back to using etherscan for all ethereum chain queries.
