### ISSUE TITLE
Node version mismatch in zmq in dev environment

### ISSUE THREAD

**Issue by lordi** [rotkehlchenio/rotkehlchen#36]
When launching the GUI I get the following error on the developer console:

```
The module '(...)/rotkehlchen/node_modules/zmq/build/Release/zmq.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 59. This version of Node.js requires
NODE_MODULE_VERSION 57. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
```

I run Arch Linux and followed the steps from the README:

```
% node --version
v9.11.1
```

Also trying to run
```
npm rebuild zmq
```
did recompile the module but did not change anything about the error.

Do you have any hints or ideas about things to try?

**Comment by LefterisJP** [comment]
@lordi I also run Archlinux so we are gonna find a solution to this fast.

Did you do `$ npm install --runtime=electron --target=1.8.4`?

If yes, then right after it can you try:

```
$ PYTHON=/usr/bin/python2.7 ./node_modules/.bin/electron-rebuild
```

and then try to run it with `npm run` ?

**Comment by lordi** [comment]
Thanks, this worked! (with ``npm start``)

It also works with just ``./node_modules/.bin/electron-rebuild`` without the modified PYTHON env var. Maybe this should be added to the install instructions?

By the way I think the README became quite large with specific install instructions. Maybe these should be moved to another file like install.md and then linked from the README in order to please new users with a clean first impression :-) If you want I can make a PR which moves the install instructions and adds the electron-rebuild line to it for Linux.

**Comment by LefterisJP** [comment]
>  If you want I can make a PR which moves the install instructions and adds the electron-rebuild line to it for Linux.

Sure please do. And thanks in advance :)
