### ISSUE TITLE
Fetching data from Kraken fails

### ISSUE THREAD

**Issue by tschubotz** [rotkehlchenio/rotkehlchen#390]
## Problem Definition

After adding API info for Kraken, rotkehlchen seems unable to fetch data successfully due to the following error:
```
Exchange query error
Querying undefined died because of: Could not find a BTC tradeable pair in kraken for "BSV". Check the logs for more details.
```

Relevant entry from `rotkehlchen.log`:

```
30/06/2019 21:14:44 CEST -- ERROR:rotkehlchen.server:Greenlet for task 0 dies with exception: Could not find a BTC tradeable pair in kraken for "BSV".
Exception Name: <class 'ValueError'>
Exception Info: Could not find a BTC tradeable pair in kraken for "BSV"
Traceback:
   File "src/gevent/greenlet.py", line 716, in gevent._greenlet.Greenlet.run
  File "rotkehlchen/server.py", line 118, in _query_async
  File "rotkehlchen/server.py", line 187, in query_exchange_balances
  File "rotkehlchen/utils.py", line 93, in wrapper
  File "rotkehlchen/kraken.py", line 448, in query_balances
  File "rotkehlchen/kraken.py", line 413, in find_fiat_price
```
### System Description
`Darwin asdf 18.6.0 Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64 x86_64`
I was using release `v0.6.0` of rotkehlchen.

**Comment by LefterisJP** [comment]
Hey @tschubotz! Thanks for trying out Rotkehlchen. v0.6.0 is pretty old. We are rather close to a v1.0 release. Still trying to stabilize and test the software in preparation for it.

This problem should be solved there. It should also work flawlessly in latest master if you are feeling adventurous and want to try to [build from source](https://rotkehlchen.readthedocs.io/en/latest/installation_guide.html#build-from-source).

**Comment by LefterisJP** [comment]
@tschubotz Can you try with v1.0? It was released yesterday. Can you tell us if the problem persists?

**Comment by tschubotz** [comment]
Works with v1.0. Problem seems to be resolved.

**Comment by LefterisJP** [comment]
Thank you @tschubotz, this is great to hear. Am here for everything else you need during your experience with v1.0.
