### ISSUE TITLE
Kraken setup

### ISSUE THREAD

**Issue by InoMurko** [rotkehlchenio/rotkehlchen#442]
## Problem Definition

Adding Kraken's API credentials fails and then I'm unable to set it up.
<img width="713" alt="Screen Shot 2019-08-04 at 10 01 24" src="https://user-images.githubusercontent.com/2582555/62421238-04514100-b69f-11e9-84b7-0a80e3624cce.png">
<img width="295" alt="Screen Shot 2019-08-04 at 10 00 09" src="https://user-images.githubusercontent.com/2582555/62421239-04e9d780-b69f-11e9-8d0c-b8c795248b9e.png">

### System Description

Here add a detailed description of your system, e.g. output of the following script:

```
Darwin Inos-MacBook-Pro.local 18.2.0 Darwin Kernel Version 18.2.0: Thu Dec 20 20:46:53 PST 2018; root:xnu-4903.241.1~1/RELEASE_X86_64 x86_64

rotkehlchenio 1.0.1
```

**Comment by InoMurko** [comment]
Logging out and back in "kinda" solved the problem but then I get:
```
Error at setup of kraken: EGeneral:Permission denied
```

**Comment by LefterisJP** [comment]
If you get a permission denied then this may mean that you have copy pasted the api key wrong. Let me try to reproduce your issue as I also have a kraken api key.

**Comment by InoMurko** [comment]
Found another one:
Immediately after you successfully provision a new exchange, the left dashboard button `Exchange Trades` stops being responsive.

**Comment by LefterisJP** [comment]
@InoMurko The Exchange trades button is actually a "TODO" It does not work yet. There is an issue for this: https://github.com/rotkehlchenio/rotkehlchen/issues/284

**Comment by LefterisJP** [comment]
@InoMurko So can you tell me does adding a kraken api key work for you? I just tried it on a new clean account and it worked without problems using the latest master. But it should generally work.

As I said [here](https://github.com/rotkehlchenio/rotkehlchen/issues/442#issuecomment-517983023) the only reason I can imagine this may not work is that the key and the secret (private key) combination is invalid.

**Comment by InoMurko** [comment]
What it was is actually (https://github.com/rotkehlchenio/rotkehlchen/issues/442#issuecomment-517982929):
Query Funds needs to be enabled on Kraken API. Still, this I think could be vocalized better and if an exchange  provisioning process is faulty, the app shouldn't "register" it.

**Comment by LefterisJP** [comment]
I agree with your comment! This behaviour of kraken API is new. I will see what I can do. Thank you for opening an issue for this.
