### ISSUE TITLE
Failed to deserialize at Generate report

### ISSUE THREAD

**Issue by InoMurko** [rotkehlchenio/rotkehlchen#443]
## Problem Definition
Binance and Kraken is setup
Tax report from 2010 till 2019.
Click Generate report
```
Querying trade history died because of: Failed to deserialize 1558090954.7199 kraken timestamp entry from an FVal. Check the logs for more details
```
### System Description

Rotkehlchen 1.0.1

```
18.2.0 Darwin Kernel Version 18.2.0: Thu Dec 20 20:46:53 PST 2018; root:xnu-4903.241.1~1/RELEASE_X86_64 x86_64
```

**Comment by LefterisJP** [comment]
Ah that looks like something. Let me try to reproduce. I think I have an idea.

**Comment by LefterisJP** [comment]
Confirming this as a reproducible bug. Will provide a fix soon.

**Comment by LefterisJP** [comment]
@InoMurko If you can run from source please try the fix from this PR: https://github.com/rotkehlchenio/rotkehlchen/pull/444

If not wait till the next release. I will make it soon since this bug is breaking the tax report experience for kraken users.

**Comment by LefterisJP** [comment]
@InoMurko Fix for both this and the other issue you reported is included in the new release just made today: https://github.com/rotkehlchenio/rotkehlchen/releases/tag/v1.0.2

**Comment by InoMurko** [comment]
@LefterisJP sorry I was not around earlier. Tested all of it and it works!
