### ISSUE TITLE
Add the ability to delete erroneously added accounts

### ISSUE THREAD

**Issue by chevdor** [rotkehlchenio/rotkehlchen#462]
## Abstract

Currently one can add an account but not remove it.

## Motivation

Humans make mistakes...

## Specification

Add a way to delete an account from the list

**Comment by LefterisJP** [comment]
Hey @chevdor!

Accounts are definitely deletable. Right click on the table showing your accounts under the user settings and click `Delete`

**Comment by chevdor** [comment]
My bad, I missed that one. Indeed, right clicking shows a popup that allows deleting and it works, thus closing this issue.

![image](https://user-images.githubusercontent.com/738724/62917803-f3d74f80-bd9d-11e9-8f9b-1d80718ab991.png)
