### ISSUE TITLE
Tax reports should convert start/end date to local time

### ISSUE THREAD

**Issue by chevdor** [rotkehlchenio/rotkehlchen#463]
Today is 2019-08-12 and it is 12:59.

![image](https://user-images.githubusercontent.com/738724/62860616-fa63b980-bd00-11e9-9d59-c28089041afd.png)

**Comment by chevdor** [comment]
The same query with a time of 0:00 seems to pass the validation.

**Comment by chevdor** [comment]
This is localisation issue. It is now 13:04 and the queries work until 11:00.
I am on Berlin time as well.

**Comment by LefterisJP** [comment]
Nicely spotted. This is indeed a localization error. All times in the backend are in UTC. A conversion should be done from the UI. Will be done by the next release.

**Comment by kelsos** [comment]
@LefterisJP I will pick it tomorrow. Also should keep that in mind for the rewrite.

**Comment by LefterisJP** [comment]
Thank you @kelsos. Should be easy. As for the rewrite I guess as long as it's properly rebased it will work out fine.

**Comment by chevdor** [comment]
I guess it would be also nice for the user experience to *allow* dates in the future.
If the queries really fail when doing so, we could crop the date to `now` if in the future.
