### ISSUE TITLE
Fail to start 'as app' on OSX

### ISSUE THREAD

**Issue by chevdor** [rotkehlchenio/rotkehlchen#464]
## Problem Definition

Starting Rotkehlchen from the Apps Menu on OSX fails:
![image](https://user-images.githubusercontent.com/738724/62917322-136d7880-bd9c-11e9-9c11-0d142b350a29.png)

Starting from the shell works.

Rotkehlchen also logs debug information to the `rotkehlchen.log` file but I did not find this file under:
`~/LIb../App.. Supp../rot...`
or `~/.rot...`

**Comment by chevdor** [comment]
While testing to provide more information for this issue, I realised the issue is different than my initial take.

In short: starting rotkehlchen twice works as workaround.

My 2 cents:
- first start:
    - rotk starts the backend at start, it takes a few seconds
    - then the ui starts and fails (check too early?)
- second start:
    - backend is still running
    - the second start finds the backend and uses it successfully

**Comment by chevdor** [comment]
After more checking: the workaround I mentioned above does not work. The error does not show up but signing in is not possible and times out after 30s.
![image](https://user-images.githubusercontent.com/738724/62917687-8a574100-bd9d-11e9-9491-7ac66e04f933.png)

So far, the only solution I found to start the app is to open a shell and:
```
cd /Applications/rotkehlchen.app/Contents/MacOS
./rotkehlchen &
```

**Comment by LefterisJP** [comment]
This is a known problem. Which executable did you click? https://rotkehlchen.readthedocs.io/en/latest/installation_guide.html#troubleshooting

There is another issue for it here: https://github.com/rotkehlchenio/rotkehlchen/issues/426

**Comment by chevdor** [comment]
I am actually not clicking anything, I am using Alfred but I guess that does not matter.

It picks however the single Rotkehlchen available in my Applications' list. I do not have 2 choices.

As far as the install went, I copied Rotkehlchen.app into my Applications folder and that´s it.

**Comment by LefterisJP** [comment]
Yeah that's the problem. I know this is the "OSX" way ... and I want us to go towards that, but that does not work. The only way is to unzip the zip file from Releases, and click/or execute via command line the executable shown in the docs I linked below.

As per the other issue any other way of executing results in problems like the one you see. 

It's on the top of my TODO list ... but I am also kind of puzzled on how to fix this as I am not an OSX developer and have only an old macbook I got from someone to test these stuff.

**Comment by chevdor** [comment]
No worries, this is not nice for first time users but there are ways to get it to work so this is no blocker. At least the issue is logged. I may revisit and see if I can help fix that once I find a little time...

**Comment by LefterisJP** [comment]
Should be fixed in 1.0.3

**Comment by chevdor** [comment]
I confirm, now the install is just as you expect on OSX. Drag&Drop, validate security, open. Well done!

**Comment by LefterisJP** [comment]
Thank you @chevdor ! :)

It was all due to the sandboxing OSX does. It puts new apps in a special directory where they have no permissions to write any new files. So writting the logfile in that directory failed with a permission error and crashed the app :)
