### ISSUE TITLE
PRL token not removable from "ETH tokens to track"

### ISSUE THREAD

**Issue by smurfer** [rotkehlchenio/rotkehlchen#467]
## Problem Definition

added PRL token, wanted to remove it again. Pops up "Token Removal Error" :
EthereumToken(identifier='PRL', name='Oyster', symbol='PRL', active=False, asset_type=, started=1506816000, ended=1545177600, forked=None, swapped_for=None, ethereum_address='0x1844b21593262668B7248d0f57a220CaaBA46ab9', decimals=18).
Appears to be gone from list, but when refreshed, PRL is still there.

related log:
16/08/2019 08:57:07 W. Europe Daylight Time -- DEBUG:rotkehlchen.inquirer:Get usd price from cryptocompare asset=Oyster
16/08/2019 08:57:07 W. Europe Daylight Time -- ERROR:rotkehlchen.inquirer:Cryptocompare usd price query failed asset=Oyster, error=There is no data for the symbol PRL .

### System Description
Windows 1903

**Comment by LefterisJP** [comment]
Hello @smurfer!

Thanks for using Rotki and opening up an issue.

So a question. If you restart the application is the token still there?

**Comment by smurfer** [comment]
yes...

**Comment by LefterisJP** [comment]
Hey @smurfer I found the issue with the PRL token. It's a twofold issue.

1. Cryptocompare has no historical price data for it even though it's on the website. I already contacted them about it and they are looking at it.

2. Somehow the price query failing makes the token removal fail. I will fix that soon and the fix will be included in the next release.
