### ISSUE TITLE
Problem with OTC trades

### ISSUE THREAD

**Issue by smurfer** [rotkehlchenio/rotkehlchen#469]
## Problem Definition

entered an OTC trade: EUR_BTC, type "buy" (did not change the default drop down), amount 0.5, rate 351, time some date in 2013.

the entry shows up in the OTC trades list, but with an empty "type", and when I open the OTC trades list from the menu again, a windows error dialog pops up (apparently from the db system, not rotki; screen shot see link: 
![image](https://user-images.githubusercontent.com/7305237/63216366-3ef1b980-c134-11e9-8025-87e23d7a6795.png)
It seems that the type is not stored in the db, but is tried to be retrieved, which fails.

two further issues:
- I did not find a way to delete transactions.
- The "Exchange Trades" list is empty

### System Description
Windows 1903

**Comment by LefterisJP** [comment]
Hey, thanks for opening the issue!

I will look into the problem you reported with the OTC trades.

> (apparently from the db system, not rotki; screen shot see link:

Datatable is actually in the node.js frontend. It's what creates those tables. Let me have a look and try to reproduce your problem.

As for the other comments:

> I did not find a way to delete transactions.

By right clicking on any transaction on the table below you should get a context menu with 2 options. "Edit" or "Delete".

I also just noticed this is not in the docs: https://rotkehlchen.readthedocs.io/en/latest/usage_guide.html#manually-adding-trades-or-taxable-events

So I will add this information there.


> The "Exchange Trades" list is empty

That is actually a long standing TODO and has an issue: https://github.com/rotkehlchenio/rotkehlchen/issues/284

It's very easy to do but I am waiting for the front-end rewrite from @kelsos to proceed with adding this as I don't want to mess with the frontend UI before he is finished.

**Comment by kelsos** [comment]
@LefterisJP I actually encountered the OTC trades issue when running the tests for the date conversion. I will actually fix it in the same PR.

**Comment by LefterisJP** [comment]
Oh wait so you are fixing this also in that PR? that's nice. Is there a test for it?
