### ISSUE TITLE
Interface or API

### ISSUE THREAD

**Issue by lordi** [rotkehlchenio/rotkehlchen#48]
Is is possible to access the python process via an API?

It would be nice to have a CLI or similiar able to interact with the python core.

**Comment by LefterisJP** [comment]
Yes it is actually. It's just not documented. This is what I have been using for almost a year before I started to add a UI on top of it and make rotkehlchen as it is now.

Assuming you are on a venv that has installed the requirements.txt, in one terminal you can run the python core alone like this, adjusting the arguments.

```
python -m rotkehlchen --zerorpc-port 4242 --ethrpc-port 8545
```

And then from another similar terminal (still inside the venv):

```
zerorpc --timeout 1980 tcp://localhost:4242 unlock_user username pass False unknown anything anything
```

The above corresponds to the account unlock call seen [here](https://github.com/rotkehlchenio/rotkehlchen/blob/486866234804c64ee7e7c581cc1bc7f7841bec96/rotkehlchen/server.py#L329).

Essentially all the possible calls are in the [server.py](https://github.com/rotkehlchenio/rotkehlchen/blob/486866234804c64ee7e7c581cc1bc7f7841bec96/rotkehlchen/server.py#L162) file. That's the API with which you can communicate with the python core.

The reason it's not documented is that this is supposed to be a UI application and users should not need to use the CLI. Only expert users/devs are expected to use it and thus documenting the API was not a priority.

**Comment by lordi** [comment]
Ok, super.
