### ISSUE TITLE
HeartbeatError

### ISSUE THREAD

**Issue by pkafei** [rotkehlchenio/rotkehlchen#485]
I'm unable to create a new account on Rotkehlchen. After I put in my credentials I receive a `HeartBeatError: Lost remote after 30000ms`.  Also not sure where to find the log files.

```
System Info:
 MacOS Mojave 10.14.5, 18.6.0 Darwin Kernel Version 18.6.0, 
root:xnu-4903.261.4~2/RELEASE_X86_64 x86_6

Rotkehlchen Version:

v1.0.02
```

**Comment by LefterisJP** [comment]
Hello @pkafei 

This is probably this issue: https://github.com/rotkehlchenio/rotkehlchen/issues/464
which is related to: https://github.com/rotkehlchenio/rotkehlchen/issues/426

Did you follow the instructions for OSX: https://rotkehlchen.readthedocs.io/en/latest/installation_guide.html#osx

Especially the troubleshooting guide? At the moment it's a bit counter-intuitive to start the app in OSX. Making this easier for OSX users is a high priority.
