### ISSUE TITLE
Validation on passwords

### ISSUE THREAD

**Issue by chevdor** [rotkehlchenio/rotkehlchen#503]
## Abstract

Currently, there appear to be no validation on the password content.
This lead however to issues with passwords including chars such as `_` or `=`.
When using such a password, the account seems to be (partly?) created but you cannot login.

## Motivation

Ultra smooth onboarding.

**Comment by LefterisJP** [comment]
Hey @chevdor 

I can not reproduce this problem.

I created two accounts in Linux. One with `_` as the password and one with `=`. Both worked fine. I saved a random balance and then relogged in and was there.

How did you get this? Can you give some more details?

**Comment by chevdor** [comment]
Ok, let me try that again.
What I can tell is:
- it was a fresh OSX install
- it was the first account
- I used a long random password generated from a pwd manager
- the pwd contained a _ that I removed after seeing the issue
- I then got the issue again and removed a = that was also in there
- then it worked

Not sure whether the issue occurs when there are already accounts in the DB but I will test again.

**Comment by chevdor** [comment]
I cannot reproduce.

What would be the best way to delete anything created by the App at first start so I can test that again?

**Comment by LefterisJP** [comment]
Everything created by the app is in `~/.rotkehlchen`. Also logs would go to `~/Library/Logs/rotkehlchen`

**Comment by chevdor** [comment]
I found the following folders (the bad one may be my mistake, not sure...):
- .rotkehlchen/ 
- .rotkelchen/  

and deleted both.

In ~/Library/Logs, I found:
- rotki/                   
- rotkirotki_electron.log 

Also deleted both.

I then created a new user with a similar password than the one triggering the issue previously but could not reproduce the issue.
I am sure there is still a small issue hidden somewhere but without more info, it will likely be hard to solve so I am closing this issue.

**Comment by LefterisJP** [comment]
> the bad one may be my mistake, not sure

The bad one shows that you are an OG rotkehlchen user. Very early versions had the name mispelled everywhere.

> In ~/Library/Logs, I found:
>
>rotki/
> rotkirotki_electron.log

That's interesting. Was the electron log under the `/rotki` subdirectory or not?

**Comment by chevdor** [comment]
I did not check the content and dumped it all :)
