### ISSUE TITLE
Updating decorator cache_response_timewise

### ISSUE THREAD

**Issue by anselal** [rotkehlchenio/rotkehlchen#56]
I noticed that you don't use the `functools.wraps` function in your decorator

https://github.com/rotkehlchenio/rotkehlchen/blob/91f750bed086c46ed57ebc349d70a4630d929f29/rotkehlchen/utils.py#L66

Is it OK if I update the decorator with the following line:

```python
from functools import wraps
...

def _cache_response_timewise(f):
    @wraps(f)
    def wrapper(wrappingobj, *args):
```

Using the `@wraps(f)` decorator the information `f.__name__` and `f.__doc__` won't be replaced with 
the name and the docstring of the `wrapper` function eg. `wrapper` and `None` respectively.

**Comment by LefterisJP** [comment]
Hey anselal would that introduce any overhead?

**Comment by anselal** [comment]
The function is a few lines of code but I think it is worth it since it could help while debugging.

**Comment by LefterisJP** [comment]
My question was more aimed if it would add an overhead in in performance. Since this is a decorator on all RPC calls.

**Comment by anselal** [comment]
This is what a meant with a few lines of code. 

As I understand it just copies over some attributes from the old function to the new function.

Is there a way to benchmark the RPC calls ?

**Comment by LefterisJP** [comment]
not yet. But I guess it should be fine. Overoptimization is not needed at this point.
