### ISSUE TITLE
Typo for the main python module

### ISSUE THREAD

**Issue by chevdor** [rotkehlchenio/rotkehlchen#6]
This folder https://github.com/rotkehlchenio/rotkehlchen/tree/master/rotkelchen should be called `rotkehlchen` or you may need to rename the project entirely.
After all, YOU pick the name, whether it is german or not :)

**Comment by LefterisJP** [comment]
I know .. I know :)

I have the name mispelled in most of the project. You can simply grep for `rotkelchen` and you will see how many times I mispelled it. Will just do search and replace at some point.

```
grep -r rotkelchen rotkelchen | wc -l
187
```

In my defense ... when I first started the project I wrote it as I heard it and only checked the actual spelling 3 months later.

German is hard :)

**Comment by chevdor** [comment]
Tell me about it :) I have spent only 1-2 hours on the project and I did this typo also several times.

Sorry to point out the obvious. IMO the later you do it the more troubles you will have.
I would be happy to contribute with a PR for that but I currently fail starting the server (OSX) so I currently cannot properly validate that all works fine after refactoring.

**Comment by chevdor** [comment]
Happy if I can help. You will need to state whether you want to stick with the correct german spelling or make up your own.

**Comment by LefterisJP** [comment]
Correct spelling ofcourse. I did not expect this to happen before I opened the code. Just somewhere along the line .. I just forgot about it :D
