### ISSUE TITLE
Account number not added correctly

### ISSUE THREAD

**Issue by kascheri12** [rotkehlchenio/rotkehlchen#66]
Running release v0.2.0

I try adding ETH account number: 0xaecef02c32...
Down below in the ETH accounts block, it displays: 0xaECEf02C32...

When I try right clicking and select Delete, I get "Account Deletion Error"
"Error at deleting ETH account 0xaECEf02C32... 
Input error: Tried to remove non-existing ETH account 0xaECEf02C32..."

**Comment by LefterisJP** [comment]
Hmm that's interesting. Thanks for reporting. I think I know what can be the problem. I will have a look.

As for why you got it as "0xaECEf02C32.." it's due to the application using the [EIP55](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-55.md) format.

**Comment by LefterisJP** [comment]
@kascheri12 This should be fixed now. Will start a patch release for this bug.
