### ISSUE TITLE
Install fail on OSX

### ISSUE THREAD

**Issue by chevdor** [rotkehlchenio/rotkehlchen#7]
Hi @LefterisJP 
I mainly open this one to track down my findings and solutions for OSX. 
Related to #5 

DISCLAIMER for the quick reader. Rothehlchen currently does NOT (yet) support OSX. So issues are expected.

I had similar issues with raiden. Switching from anaconda to virtualenv made things somehow simpler and did the trick for raiden.

For rotkehlchen it does not (yet) do the trick. I think this is a pure python issue that has nothing to do with the code in this repo (see how I avoid writing the name to escape typos :))

pip is lying to me:
```
$ pip install pysqlcipher3
Collecting pysqlcipher3
  Using cached pysqlcipher3-1.0.2.tar.gz
Building wheels for collected packages: pysqlcipher3
  Running setup.py bdist_wheel for pysqlcipher3 ... done
  Running setup.py clean for pysqlcipher3
Failed to build pysqlcipher3
Installing collected packages: pysqlcipher3
  Running setup.py install for pysqlcipher3 ... done
Successfully installed pysqlcipher3
(venv-rotkehlchen) $ pip uninstall pysqlcipher3
Cannot uninstall requirement pysqlcipher3, not installed
```

And reading this again, I see I got fooled... I read the end:

> Successfully installed pysqlcipher3

and missed:

> Failed to build pysqlcipher3

**Comment by LefterisJP** [comment]
Heh .. yeah this is a really annoying problem of the way `pysqlcipher3` is built. I had the same erroneous message when I built in Linux and had failures.

Make sure you got [sqlcipher](https://www.zetetic.net/sqlcipher/) properly installed first. Since pysqlcipher3 is just a python frontend for it.

**Comment by chevdor** [comment]
@LefterisJP nice hint.

`brew install sqlcipher` fixed the issue:

```
$ pip install pysqlcipher3
Collecting pysqlcipher3
  Using cached pysqlcipher3-1.0.2.tar.gz
Building wheels for collected packages: pysqlcipher3
  Running setup.py bdist_wheel for pysqlcipher3 ... done
  Stored in directory: /Users/will/Library/Caches/pip/wheels/e3/8f/fb/95190e2bfe9a073a937fffa58a762758aa9447fb5ed8386b81
Successfully built pysqlcipher3              <==== SUCCESS
Installing collected packages: pysqlcipher3
Successfully installed pysqlcipher3-1.0.2
```

that seems very rewarding:
![image](https://user-images.githubusercontent.com/738724/37705938-ede59f64-2cfd-11e8-9b5d-96e60a146e23.png)

**Comment by chevdor** [comment]
Closing this issue. The trick is `brew install sqlcipher`.
From there, after setting up the venv of your choice and making sure you use python 3.6, things are smooth to get Rotkehlchen starting.

**Comment by LefterisJP** [comment]
Nice! 

Please note: Everything can break at this point as far as (DB) compatibility is concerned at least until a first version is released. From then and on we will have DB upgrades with each version. 

I should make a guide on how to use it also.

**Comment by chevdor** [comment]
The reader has been warned :)

**Comment by LefterisJP** [comment]
Also could you maybe open a PR to document how you did it on Macoss and add to the readme? Specifically how to get the dependencies like zeromq and sqlcipher.

**Comment by chevdor** [comment]
With great pleasure. I started a new branch at the beginning, I just need to bring some order in there.
Count on that PR.
