### ISSUE TITLE
Exchange setup error: Poloniex

### ISSUE THREAD

**Issue by Phistr90** [rotkehlchenio/rotkehlchen#70]
During exchange setup:

Error at setup of poloniex: ValueError: Poloniex query for "returnFeeInfo" returned error: Nonce must be greater than 1497024011872906. You provided 1527768221649.

It shows nothing under 'Exchanges trades' and it says 'Error at setup of poloniex: Exchange poloniex is already registered' when trying again.

**Comment by LefterisJP** [comment]
That sounds like a timing issue due to the nonce setup. What happens if you restart rotkehlchen? Setup should have happened, just the feeInfo during the initial setup seems to have failed.

**Comment by LefterisJP** [comment]
@Phistr90 Have you tried again with v1.0.0? Does this still happen for you?

**Comment by LefterisJP** [comment]
Closing due to lack of feedback. If there is any similar problem please open a new issue.
